version: "3"

services:
  redis:
    container_name: redis
    image: "redis:7.0.0"
    ports:
      - "6379:6379"

  metarank_standalone:
    container_name: metarank_standalone
    image: metarank/metarank:0.5.3
    depends_on:
      - redis
    command: "standalone --config /data/config.yml --data /data/events/"
    volumes:
      - ./metarank:/data
    ports:
      - "8080:8080"
      - "6123:6123"
      - "8081:8081"

  # server:
    # container_name: server
    # depends_on:
      # - metarank_standalone
    # build:
      # context: .
      # dockerfile: Dockerfile
      # args:
        # - BUILD_CONTEXT=server
    # environment:
      # - ADDRESS=0.0.0.0
      # - METARANK_URL=http://metarank:8080
    # ports:
      # - "3001:3001"

  # frontend:
    # depends_on:
      # - redis
    # container_name: frontend
    # build:
      # context: .
      # dockerfile: Dockerfile
      # args:
        # - BUILD_CONTEXT=frontend
    # ports:
      # - "3000:3000"
