features:
  - name: popularity
    type: number
    scope: item
    source: item.popularity

  - name: genre
    type: string
    scope: item
    source: item.genres
    values:
      - drama
      - comedy
      - thriller

models:
  default:
    type: lambdamart
    path: /data/xgboost.model
    backend:
      type: xgboost
      iterations: 10
      seed: 0
    weights:
      click: 1
    features:
      - popularity
      - genre

bootstrap:
  source:
    type: file
    path file:///data/events/
  workdir: file:///data/bootstrap

inference:
  port: 8080
  host: "0.0.0.0"
  source:
    type: rest
  state:
    type: redis
    host: localhost
    format: json
